### ISSUE TITLE
doesn't show up after install.

### ISSUE THREAD

**Issue by faridosc** [leomoon-studios/blender-text-counter#1]
hi

seems like a really nice addon. after installing i try searching for it to enable it but it isn't found. 
using blender 2.75a

cheers

**Comment by leomoon** [comment]
Hello,

Please try again and download this:
https://github.com/leomoon-studios/blender-text-counter/raw/master/build/blender_text_counter.zip

If it still didn't work, please let me know.

Thanks.

**Comment by faridosc** [comment]
now it works, thanks :)
